desktop: http_uploader.c comms_posix.c http_funcs.c client.c
	gcc http_uploader.c comms_posix.c http_funcs.c client.c -o upload_desktop

nbiot: http_uploader.c comms_serial.c http_funcs.c client.c
	gcc http_uploader.c comms_serial.c http_funcs.c client.c -o upload_nbiot