desktop: http_client.c comms_posix.c http_funcs.c main.c
	gcc http_client.c comms_posix.c http_funcs.c main.c -o client_desktop

nbiot: http_client.c comms_serial.c http_funcs.c main.c
	gcc http_client.c comms_serial.c http_funcs.c main.c -o client_nbiot